### ISSUE TITLE
"setAppClientID failure"

### ISSUE THREAD

**Issue by joshbabb** [BlyncSync/cordova-plugin-jins-meme-es#3]
Error message thrown by `cordova-plugin-jins-meme-es-demo` (www/js/index.js) on setClientAppID -- likely due to MemeLib.setClientAppID expecting `Context context` as its first parameter

Need to figure out how to find out the working context from within Javascript in order to pass it on to Memelib *or else* re-implement setClientAppID in JinsMEMEES.java in order to get the working context from within Java via `Context context = this.cordova.getActivity().getApplicationContext();`

**Comment by snassi** [comment]
http://stackoverflow.com/questions/25483286/cordova-how-to-write-native-plugins-that-can-repeatedly-invoke-a-javascript-cal

**Comment by snassi** [comment]
http://d.hatena.ne.jp/yohpapa/20130819/1376947942

**Comment by patrickr** [comment]
https://cordova.apache.org/docs/en/latest/guide/platforms/android/plugin.html <cordova callback context
https://github.com/TribalyteTechnologies/cordova-plugin-myo/blob/master/src/android/com/tribalyte/plugin/myo/MyoApi.java < used in myo plugin i found

**Comment by joshbabb** [comment]
got it with private Context ctx; and ctx = cordova.getActivity().getApplicationContext(); in JinsMemeES.java::private void initialize
